### ISSUE TITLE
Epic: Add fallbacks for Noir black box functions

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/arkworks_backend#10]
```[tasklist]
### Prerequisites
- [ ] https://github.com/TomAFrench/acvm-backend-groth16/issues/1
- [ ] Bump ACVM version
```

With the prerequisites addressed, we would have a Groth16 backend that works with Noir programs which don't use black box functions (very restrictive if we have no range opcodes, etc.)

To resolve this, we could integrate existing fallbacks into this compatibility layer and return error on fallback-less black boxes, until there is more interest to build more fallbacks / native implementations for black boxes.

```[tasklist]
### Tasks
- [ ] Integrate [blackbox_fallbacks](https://github.com/noir-lang/acvm/tree/master/stdlib/src/blackbox_fallbacks) to convert black boxes into arithmetic opcodes
- [ ] Add errors for black boxes without fallbacks
```
